services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always

    ports:
    - "5432:5432" 

    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: changeme

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d userdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: node_app

    ports:
      - "3000:3000"
      - "5555:5555"
      - "5556:5556"

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    command: >
      sh -c "
      echo 'Waiting for DB...' &&
      sleep 3 &&
      npx prisma generate &&
      npx prisma migrate deploy ||
      npx prisma db push &&
      node src/server.js
      "

    restart: unless-stopped

volumes:
  pgdata: